title: Leonardo Stari
baseurl: ""
author:
  name: Leonardo Stari
  email: lstari@tohoku.ac.jp
description: >-
  Specially Appointed Research Fellow at Tohoku University. Researching environmental biotechnology, microbial community dynamics, and bioremediation of pollutants.

github_username: leostari
googlescholar_username: GGSi3PUAAAAJ

# Minima settings
minima:
  skin: auto
